name: tdarr_ci
on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  lint_bash:
    runs-on: ubuntu-latest
    name: lint_bash

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ALL_CODEBASE: true